# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: run_tests

on:
  # executa esse workflow sempre que subir uma alteracao para a branch master
  push:
    branches: [ master ]

jobs:
  build:
    # maquina onde o workflow será executado
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # vai executar 2x o mesmo workflow (paralelo) para cada node-version        
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
